start:
	python flask_service.py

test:
	curl http://127.0.0.1:5000/cloudmesh/flavor/chameleon
	curl http://127.0.0.1:5000/cloudmesh/flavor/chameleon?html

	curl http://127.0.0.1:5000/cloudmesh/image/chameleon
	curl http://127.0.0.1:5000/cloudmesh/image/chameleon?html

	curl http://127.0.0.1:5000/cloudmesh/vm/chameleon
	curl http://127.0.0.1:5000/cloudmesh/vm/chameleon?html
