
openapi: 3.0.0
info:
  title: score
  description: Return the mean accuracy on the given test data and labels.
  version: "1.0"
servers:
  - url: http://localhost/cloudmesh
    description: TODO THIS MUST BE CHANGEABLE
paths:
  /http://localhost:8000/cloudmesh:
     get:
      summary: Return the mean accuracy on the given test data and labels.
      description: Optional extended description in CommonMark or HTML.
      operationId: <class 'sklearn.linear_model._logistic.LogisticRegression'>.score
      parameters:
        - in: query
          name: X
          description: Test samples.
          schema:
            type: array
        - in: query
          name: y
          description: True labels for X.
          schema:
            type: array
        - in: query
          name: sample_weight
          description: Sample weights.
          schema:
            type: array
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: number

components:
  schemas:
    
