
openapi: 3.0.0
info:
  title: LinearRegression
  description: Ordinary least squares Linear Regression.
  version: "1.0"
servers:
  - url: http://localhost/cloudmesh
    description: TODO THIS MUST BE CHANGEABLE
paths:
  /http://localhost:8000/cloudmesh:
     get:
      summary: Ordinary least squares Linear Regression.
      description: Optional extended description in CommonMark or HTML.
      operationId: <module 'sklearn.linear_model' from '/Users/jagadeeshk/ENV3/lib/python3.8/site-packages/sklearn/linear_model/__init__.py'>.LinearRegression
      parameters:
        - in: query
          name: fit_intercept
          description: Whether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).
          schema:
            type: boolean
        - in: query
          name: normalize
          description: This parameter is ignored when ``fit_intercept`` is set to False.If True, the regressors X will be normalized before regression bysubtracting the mean and dividing by the l2-norm.If you wish to standardize, please use:class:`sklearn.preprocessing.StandardScaler` before calling ``fit`` onan estimator with ``normalize=False``.
          schema:
            type: boolean
        - in: query
          name: copy_X
          description: If True, X will be copied; else, it may be overwritten.
          schema:
            type: boolean
        - in: query
          name: n_jobs
          description: The number of jobs to use for the computation. This will only providespeedup for n_targets > 1 and sufficient large problems.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: self

components:
  schemas:
    
