# This is a basic workflow that is manually triggered

name: Check Report

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Check Report'

jobs:
  greet:
    runs-on: ubuntu-20.04

    steps:
    - name: wget markdown-check.py
      run: wget https://raw.githubusercontent.com/cybertraining-dsc/cybertraining-dsc.github.io/master/bin/markdown-check.py      
    - name: check
      run: python3 markdown-check.py paper/_index.md
