# This is a basic workflow that is manually triggered

name: Check Report

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: wget markdown-check.py
      run: wget https://raw.githubusercontent.com/cybertraining-dsc/cybertraining-dsc.github.io/master/bin/markdown-check.py      
    - name: check
      run: python3 master/bin/markdown-check.py paper/_index.md
