# This is a basic workflow that is manually triggered

name: Check Report

on: [push]

#on:
#  workflow_dispatch:
#    inputs:
#      name:
#        description: 'Check Report'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 
    - name: wget markdown-check.py
      run: wget https://raw.githubusercontent.com/cybertraining-dsc/cybertraining-dsc.github.io/main/bin/markdown-check.py      
    - name: Run Check
      run: python markdown-check.py paper/_index.md
      # run: python3 markdown-check.py report/report.md
      # run: python3 markdown-check.py project/project.md
